#pragma once
// PacketHeader.h - Application-layer packet header (R2 redesign).
//
// R2 (2026-07-27): rewrote the orphan R1 stub (which was 16B with packetId
// contradicting design §3.3 "no double-counted transport seq") into a 12B
// header that matches design §5.1. The checksum field is NOT inside the
// 12B header — it lives at the END of every frame (4B CRC32C over
// [PacketHeader 12B] [optional u32 uncompressedSize] [body]).
//
// Wire format (little-endian, packed):
//
//   off  size  field          notes
//   0    u16   msgType        0xFFFF = handshake; 0..0xFFFE = app
//   2    u16   schemaVersion  application schema version (R3+ starts using it)
//   4    u16   length         bytes between header and trailing CRC (excludes CRC itself)
//   6    u8    channel        0=Reliable, 1=Unreliable (R4 expands to 4 channels)
//   7    u8    flags          PacketFlag bitset
//   8    u32   timestampMs    sender clock ms; Replication interp uses it (R3+)
//
// Plain frame:
//   [PacketHeader 12B] [body N] [CRC32C 4B]   where length = N
//
// Compressed frame (PacketFlag::Compressed set):
//   [PacketHeader 12B] [u32 uncSize 4B] [lz4 block C] [CRC32C 4B]
//   where length = 4 + C
//
// Fragmented frames (PacketFlag::Fragmented set) — each fragment is its
// own sealed frame; the body of each is [FragmentHeader 8B][chunk].
// The LAST fragment is variable length (Ct <= chunkSize for any non-last).
// Compressed and Fragmented are mutually exclusive — compress the whole
// payload first, then fragment if it still exceeds MTU.

#include <AYCore.h>
#include <cstdint>
#include <cstddef>

#if defined(_MSC_VER)
    #pragma pack(push, 1)
#endif

namespace ayt::net
{

// =============================================================================
// PacketHeader - 12 bytes
// =============================================================================
struct PacketHeader {
    uint16_t msgType;
    uint16_t schemaVersion;
    uint16_t length;
    uint8_t  channel;
    uint8_t  flags;
    uint32_t timestampMs;

#if defined(__GNUC__) || defined(__clang__)
    __attribute__((packed))
#endif
};

#if defined(_MSC_VER)
    #pragma pack(pop)
#endif

// Layout assertions via offsetof — robust against any pragma-pack nesting
// that may happen during transitive includes. Struct size is 12 only if
// these offsets line up AND no earlier header left pack(1) unbalanced.
static_assert(offsetof(PacketHeader, msgType)       == 0, "PacketHeader.msgType must be at 0");
static_assert(offsetof(PacketHeader, schemaVersion) == 2, "PacketHeader.schemaVersion must be at 2");
static_assert(offsetof(PacketHeader, length)        == 4, "PacketHeader.length must be at 4");
static_assert(offsetof(PacketHeader, channel)       == 6, "PacketHeader.channel must be at 6");
static_assert(offsetof(PacketHeader, flags)         == 7, "PacketHeader.flags must be at 7");
static_assert(offsetof(PacketHeader, timestampMs)   == 8, "PacketHeader.timestampMs must be at 8");
static_assert(sizeof(PacketHeader) == 12, "PacketHeader must be 12 bytes (R2 §5.1)");

// =============================================================================
// FragmentHeader - 8 bytes (precedes each fragment's chunk)
// =============================================================================
struct FragmentHeader {
    uint32_t fragmentId;     // per-packet-local, generated by PacketAssembler
    uint16_t fragmentIndex;  // 0-based
    uint16_t fragmentCount;

#if defined(__GNUC__) || defined(__clang__)
    __attribute__((packed))
#endif
};

static_assert(offsetof(FragmentHeader, fragmentId)    == 0, "FragmentHeader.fragmentId must be at 0");
static_assert(offsetof(FragmentHeader, fragmentIndex) == 4, "FragmentHeader.fragmentIndex must be at 4");
static_assert(offsetof(FragmentHeader, fragmentCount) == 6, "FragmentHeader.fragmentCount must be at 6");
static_assert(sizeof(FragmentHeader) == 8, "FragmentHeader must be 8 bytes");

// =============================================================================
// PacketFlags - bitmask applied to PacketHeader.flags
//
// R2: removed PacketFlag::Encrypted (design §3.3 — encryption is exclusively
// GNS's job via DTLS + AES-GCM; application layer must NOT pretend to
// re-encrypt). Removed PacketFlag::Reliable because channel carries the
// reliable/unreliable semantic and GNS already provides reliable transport.
// =============================================================================
enum class PacketFlag : uint8_t {
    None       = 0,
    Fragmented = 1 << 0,
    Compressed = 1 << 1,
    RequiresAck = 1 << 2, // R4.1-B: receiver must echo seq on CHANNEL_ACK
};

inline PacketFlag operator|(PacketFlag a, PacketFlag b) {
    return static_cast<PacketFlag>(
        static_cast<uint8_t>(a) | static_cast<uint8_t>(b));
}

inline PacketFlag& operator|=(PacketFlag& a, PacketFlag b) {
    a = a | b;
    return a;
}

inline bool hasFlag(uint8_t flags, PacketFlag f) {
    return (flags & static_cast<uint8_t>(f)) != 0;
}

} // namespace ayt::net